deploy_version: 0.1.20
image_tag: latest

applications:
  - name: expensabot
    image: pennlabs/expensabot
    secret: expensabot
    ingress:
      hosts:
        - host: expensabot.pennlabs.org
          paths: ["/"]
